@apiKey = whoops
@fipscode = MN

GET https://waterbeacon-api.azurewebsites.net/api/waterbeaconapi?code={{apiKey}}&fipscode={{fipscode}}

###
GET https://waterbeacon-api.azurewebsites.net/api/waterbeaconapi?code={{apiKey}}
